WITH p AS (
    SELECT
        TO_DATE(?, 'DDMMYYYY') AS start_dt,
        TO_DATE(?, 'DDMMYYYY') + 1 AS end_dt
    FROM dual
),
d AS (
    SELECT
        ph.ROWID AS rid,
        ph.MODULE_ID,
        ph.PARAM_NAME,
        ph.CREATE_DTTS,

        ph.VALUE,
        LEAD(ph.VALUE) OVER (
            PARTITION BY ph.MODULE_ID, ph.PARAM_NAME
            ORDER BY ph.CREATE_DTTS DESC, ph.ROWID DESC
        ) AS PREV_VALUE,

        ph.LSL,
        LEAD(ph.LSL) OVER (
            PARTITION BY ph.MODULE_ID, ph.PARAM_NAME
            ORDER BY ph.CREATE_DTTS DESC, ph.ROWID DESC
        ) AS PREV_LSL,

        ph.USL,
        LEAD(ph.USL) OVER (
            PARTITION BY ph.MODULE_ID, ph.PARAM_NAME
            ORDER BY ph.CREATE_DTTS DESC, ph.ROWID DESC
        ) AS PREV_USL,

        LEAD(ph.CREATE_DTTS) OVER (
            PARTITION BY ph.MODULE_ID, ph.PARAM_NAME
            ORDER BY ph.CREATE_DTTS DESC, ph.ROWID DESC
        ) AS PREV_CREATE_DTTS

    FROM PARAMETER_HISTORY ph
    CROSS JOIN p
    WHERE ph.CREATE_DTTS >= p.start_dt
      AND ph.CREATE_DTTS <  p.end_dt
),
c AS (
    SELECT
        d.*,

        CASE
            WHEN DECODE(d.PREV_VALUE, d.VALUE, 0, 1) = 1
            THEN 1 ELSE 0
        END AS VALUE_CHANGED,

        CASE
            WHEN DECODE(d.PREV_LSL, d.LSL, 0, 1) = 1
            THEN 1 ELSE 0
        END AS LSL_CHANGED,

        CASE
            WHEN DECODE(d.PREV_USL, d.USL, 0, 1) = 1
            THEN 1 ELSE 0
        END AS USL_CHANGED

    FROM d
    WHERE d.PREV_CREATE_DTTS IS NOT NULL
      AND d.PREV_VALUE IS NOT NULL
      AND d.PREV_LSL IS NOT NULL
      AND d.PREV_USL IS NOT NULL
      AND d.VALUE IS NOT NULL
      AND d.LSL IS NOT NULL
      AND d.USL IS NOT NULL
      AND (
             DECODE(d.PREV_VALUE, d.VALUE, 0, 1) = 1
          OR DECODE(d.PREV_LSL, d.LSL, 0, 1) = 1
          OR DECODE(d.PREV_USL, d.USL, 0, 1) = 1
      )
)
SELECT
    MODULE_ID,
    PARAM_NAME,

    PREV_CREATE_DTTS AS PREVIOUS_CHANGE_TIME,
    CREATE_DTTS AS CURRENT_CHANGE_TIME,

    CASE WHEN VALUE_CHANGED = 1 THEN PREV_VALUE END AS PREV_VALUE,
    CASE WHEN VALUE_CHANGED = 1 THEN VALUE END AS VALUE,

    CASE WHEN LSL_CHANGED = 1 THEN PREV_LSL END AS PREV_LSL,
    CASE WHEN LSL_CHANGED = 1 THEN LSL END AS LSL,

    CASE WHEN USL_CHANGED = 1 THEN PREV_USL END AS PREV_USL,
    CASE WHEN USL_CHANGED = 1 THEN USL END AS USL,

    RTRIM(
          CASE WHEN VALUE_CHANGED = 1 THEN 'VALUE_CHANGED|' END
       || CASE WHEN LSL_CHANGED = 1 THEN 'LSL_CHANGED|' END
       || CASE WHEN USL_CHANGED = 1 THEN 'USL_CHANGED|' END,
       '|'
    ) AS CHANGE_TYPE

FROM c
ORDER BY
    MODULE_ID,
    PARAM_NAME,
    CURRENT_CHANGE_TIME;
