WITH PARAMS AS (
    SELECT SYSDATE AS CURRENT_TIME
    FROM DUAL
),
STEP_MAPPING AS (
    SELECT 1 AS SORT_NO, 'POL' AS AREANAME, 'ME030' AS STEPID FROM DUAL
    UNION ALL
    SELECT 2, 'TUFFY/CRD', 'ME140' FROM DUAL
    UNION ALL
    SELECT 3, 'LAMI', 'ME170' FROM DUAL
    UNION ALL
    SELECT 4, 'UV', 'ME220' FROM DUAL
    UNION ALL
    SELECT 5, 'WFD', 'ME240' FROM DUAL
),
EQP_ACTIVITY AS (
    SELECT
        M.SORT_NO,
        M.AREANAME,
        M.STEPID,
        T.EQPID,

        MAX(
            CASE
                WHEN T.RPTDATE >= P.CURRENT_TIME - INTERVAL '4' HOUR
                THEN 1
                ELSE 0
            END
        ) AS EXISTS_LAST_4_HOURS,

        SUM(
            CASE
                WHEN UPPER(TRIM(T.ACTIVITY)) = 'TRACKOUT'
                THEN 1
                ELSE 0
            END
        ) AS TRACKOUT_COUNT_LAST_5_HOURS

    FROM STEP_MAPPING M
    CROSS JOIN PARAMS P
    JOIN YOUR_TABLE T
      ON T.AREANAME = M.AREANAME
     AND T.STEPID = M.STEPID
     AND T.RPTDATE >= P.CURRENT_TIME - INTERVAL '5' HOUR

    GROUP BY
        M.SORT_NO,
        M.AREANAME,
        M.STEPID,
        T.EQPID
)
SELECT
    M.AREANAME,
    M.STEPID,
    A.EQPID,
    NVL(A.TRACKOUT_COUNT_LAST_5_HOURS, 0)
        AS TRACKOUT_COUNT_LAST_5_HOURS,

    CASE
        WHEN NVL(A.TRACKOUT_COUNT_LAST_5_HOURS, 0) > 0
        THEN 'YES'
        ELSE 'NO'
    END AS HAS_TRACKOUT,

    CASE
        WHEN NVL(A.TRACKOUT_COUNT_LAST_5_HOURS, 0) > 0
        THEN 'OK'
        ELSE 'NOT_OK'
    END AS STATUS

FROM STEP_MAPPING M
LEFT JOIN EQP_ACTIVITY A
  ON A.AREANAME = M.AREANAME
 AND A.STEPID = M.STEPID
 AND A.EXISTS_LAST_4_HOURS = 1

ORDER BY
    M.SORT_NO,
    A.EQPID;
