WITH STEP_MAPPING AS (
    SELECT
        1 AS SORT_NO,
        'POL' AS CURRENT_AREANAME,
        'ME050' AS CURRENT_STEPID,
        'IQC/CLN' AS PREVIOUS_AREANAME,
        'ME030' AS PREVIOUS_STEPID
    FROM DUAL

    UNION ALL

    SELECT
        2,
        'TUFFY/CRD',
        'ME170',
        'T-FOF',
        'ME140'
    FROM DUAL

    UNION ALL

    SELECT
        3,
        'LAMI',
        'ME210',
        'TUFFY/CRD',
        'ME170'
    FROM DUAL

    UNION ALL

    SELECT
        4,
        'WFD',
        'ME250',
        'UV',
        'ME240'
    FROM DUAL
),

/* Check whether data exists at the current process
   during the last 4 hours */
CURRENT_PROCESS_DATA AS (
    SELECT
        M.CURRENT_AREANAME,
        M.CURRENT_STEPID,
        COUNT(*) AS CURRENT_DATA_COUNT
    FROM STEP_MAPPING M
    JOIN YOUR_TABLE T
      ON T.AREANAME = M.CURRENT_AREANAME
     AND T.STEPID = M.CURRENT_STEPID
     AND T.RPTDATE >= SYSDATE - INTERVAL '4' HOUR
    GROUP BY
        M.CURRENT_AREANAME,
        M.CURRENT_STEPID
),

/* Check TrackOut at the previous process
   during the last 5 hours */
PREVIOUS_TRACKOUT_DATA AS (
    SELECT
        M.CURRENT_AREANAME,
        M.CURRENT_STEPID,
        COUNT(*) AS TRACKOUT_COUNT
    FROM STEP_MAPPING M
    JOIN YOUR_TABLE T
      ON T.AREANAME = M.PREVIOUS_AREANAME
     AND T.STEPID = M.PREVIOUS_STEPID
     AND T.ACTIVITY = 'TrackOut'
     AND T.RPTDATE >= SYSDATE - INTERVAL '5' HOUR
    GROUP BY
        M.CURRENT_AREANAME,
        M.CURRENT_STEPID
)

SELECT
    M.CURRENT_AREANAME,
    M.CURRENT_STEPID,
    M.PREVIOUS_AREANAME,
    M.PREVIOUS_STEPID,

    NVL(C.CURRENT_DATA_COUNT, 0) AS CURRENT_DATA_COUNT_LAST_4_HOURS,

    NVL(P.TRACKOUT_COUNT, 0) AS PREVIOUS_TRACKOUT_COUNT_LAST_5_HOURS,

    CASE
        WHEN NVL(C.CURRENT_DATA_COUNT, 0) = 0
        THEN 'NO_CURRENT_DATA'

        WHEN NVL(P.TRACKOUT_COUNT, 0) = 0
        THEN 'NOT_OK'

        ELSE 'OK'
    END AS STATUS

FROM STEP_MAPPING M

LEFT JOIN CURRENT_PROCESS_DATA C
  ON C.CURRENT_AREANAME = M.CURRENT_AREANAME
 AND C.CURRENT_STEPID = M.CURRENT_STEPID

LEFT JOIN PREVIOUS_TRACKOUT_DATA P
  ON P.CURRENT_AREANAME = M.CURRENT_AREANAME
 AND P.CURRENT_STEPID = M.CURRENT_STEPID

ORDER BY M.SORT_NO;
