WITH STEP_MAPPING AS (
    SELECT 1 AS SORT_NO,
           'POL' AS AREANAME,
           'ME050' AS CURRENT_STEPID,
           'ME030' AS PREVIOUS_STEPID
    FROM DUAL

    UNION ALL
    SELECT 2, 'TUFFY/CRD', 'ME170', 'ME140' FROM DUAL

    UNION ALL
    SELECT 3, 'LAMI', 'ME210', 'ME170' FROM DUAL

    UNION ALL
    SELECT 4, 'UV', 'ME240', 'ME220' FROM DUAL

    UNION ALL
    SELECT 5, 'WFD', 'ME250', 'ME240' FROM DUAL
),

/* Get all EQPIDs linked with AREANAME and previous STEPID */
EQP_DATA AS (
    SELECT DISTINCT
        M.SORT_NO,
        M.AREANAME,
        M.CURRENT_STEPID,
        M.PREVIOUS_STEPID,
        T.PRODUCTID,
        T.EQPID
    FROM STEP_MAPPING M
    LEFT JOIN YOUR_TABLE T
        ON UPPER(TRIM(T.AREANAME)) = M.AREANAME
       AND TRIM(T.STEPID) = M.PREVIOUS_STEPID
       AND T.EQPID IS NOT NULL
),

/* Count TrackOut during the last 5 hours */
TRACKOUT_DATA AS (
    SELECT
        M.AREANAME,
        M.PREVIOUS_STEPID,
        T.PRODUCTID,
        T.EQPID,
        COUNT(*) AS TRACKOUT_COUNT
    FROM STEP_MAPPING M
    JOIN YOUR_TABLE T
        ON UPPER(TRIM(T.AREANAME)) = M.AREANAME
       AND TRIM(T.STEPID) = M.PREVIOUS_STEPID
    WHERE UPPER(TRIM(T.ACTIVITY)) = 'TRACKOUT'
      AND T.RPTDATE >= SYSDATE - (5 / 24)
    GROUP BY
        M.AREANAME,
        M.PREVIOUS_STEPID,
        T.PRODUCTID,
        T.EQPID
)

SELECT
    E.AREANAME,
    E.CURRENT_STEPID,
    E.PREVIOUS_STEPID,
    E.PRODUCTID,
    E.EQPID,
    NVL(T.TRACKOUT_COUNT, 0) AS TRACKOUT_COUNT_LAST_5_HOURS,
    CASE
        WHEN NVL(T.TRACKOUT_COUNT, 0) = 0
            THEN 'NOT_OK'
        ELSE 'OK'
    END AS STATUS
FROM EQP_DATA E
LEFT JOIN TRACKOUT_DATA T
    ON T.AREANAME = E.AREANAME
   AND T.PREVIOUS_STEPID = E.PREVIOUS_STEPID
   AND T.EQPID = E.EQPID
   AND (
        T.PRODUCTID = E.PRODUCTID
        OR (
            T.PRODUCTID IS NULL
            AND E.PRODUCTID IS NULL
        )
   )
ORDER BY
    E.SORT_NO,
    E.PRODUCTID,
    E.EQPID;
